version: '3.1'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: C4rPnxT82r
      MYSQL_DATABASE: gctest
      MYSQL_USER: gctestman
      MYSQL_PASSWORD: C4rPnxT82r
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 8080:80
    depends_on:
      - db

volumes:
  db_data:
